### ISSUE TITLE
wait steps with continue_on_failure blow up

### ISSUE THREAD

**Issue by jack1902** [Zegocover/git-diff-conditional-buildkite-plugin#17]
### Description

When a pipeline uses a wait step like the below, it will cause the plugin to blow up:

```yaml
steps:
  - wait: ~
    continue_on_failure: true
```

### Steps to Reproduce

* Have a template pipeline that contains the wait step which is a `dict`

## Desired Change

`wait` steps with `continue_on_failure` to work with the plugin
